version: '3.9'

services:
  db:
    image: 'mongo:6.0.5'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=${DB_AUTHENTICATION_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - '27017-27019:27017-27019'
    networks:
      - ports-network
    restart: always
    volumes:
      - ./mongo-volume:/data

  app:
    build: .
    volumes:
      - .:/opt/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - ports-network
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  ports-network:
    driver: bridge
