version: '3.9'

services:
  db:
    image: 'mongo:6.0.5'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=${DB_AUTHENTICATION_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_USER_PASSWORD}

    ports:
      - '27017-27019:27017-27019'
    networks:
      - ports-network
    restart: always

networks:
  ports-network:
    driver: bridge
